# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - run: pip install coverage
    - run: coverage run ./test/test_engine.py -g all

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Run tests
      run: |
        python ./test/test_engine.py -g all
    - run: echo "🍏 This job's status is ${{ job.status }}."
    - run: echo "Test Workflow is successfully completed. 😊"